#include "tcp_typedefs.h"
const char* COMMAND_TYPE_STRINGS[] = {
    [COMMAND_ECHO] = "ECHO",
    [COMMAND_STOP] = "STOP",
    [COMMAND_FORWARD] = "FORWARD",
    [COMMAND_BACKWARDS] = "BACKWARD",
    [COMMAND_LEFT] = "LEFT",
    [COMMAND_RIGHT] = "RIGHT",
    [COMMAND_UNDEFINED] = "UNDEFINED",
};
bool ECHO_MODE_ENABLED = true;
